# Generated by Django 5.1.4 on 2024-12-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campo_de_juego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("ubicacion", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Equipos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_equipo", models.CharField(max_length=20)),
                ("nombre_tecnico", models.CharField(max_length=30)),
                ("jugador1", models.CharField(max_length=30)),
                ("jugador2", models.CharField(max_length=30)),
                ("jugador3", models.CharField(max_length=30)),
                ("jugador4", models.CharField(max_length=30)),
                ("jugador5", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Patrocinadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
            ],
        ),
    ]
