# Generated by Django 5.1.4 on 2024-12-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_pagina", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_equipo", models.CharField(max_length=50)),
                ("nombre_tecnico", models.CharField(max_length=30)),
                ("jugador1", models.CharField(max_length=30)),
                ("jugador2", models.CharField(max_length=30)),
                ("jugador3", models.CharField(max_length=30)),
                ("jugador4", models.CharField(max_length=30)),
                ("jugador5", models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name="Campo_de_juego",
            new_name="Campos_de_juego",
        ),
        migrations.RenameModel(
            old_name="Patrocinadores",
            new_name="Patrocinador",
        ),
        migrations.DeleteModel(
            name="Equipos",
        ),
    ]
